const productos=[
    {id:'1',idCategoria:'1',img:'../public/imgProductos/img1.jpg',titulo:'Notebook Asus X515EA i3 1115G4 4Gb SSD 256Gb 15.6 FHD Free',precio:'$713889',descripcion:'Ya sea para trabajar o jugar, ASUS X515 es la laptop para el día a día que ofrece un rendimiento potente y efectos visuales envolventes. Su pantalla NanoEdge cuenta con amplios ángulos de visión de 178° y un revestimiento mate antirreflejo para una experiencia verdaderamente atractiva.'},
    {id:'2',idCategoria:'1',img:'../public/imgProductos/img2.jpg',titulo:'OUTLET NOTEBOOK XPG XENIA 14 I5 1135G7 512GB 16GB 14 W10',precio:'$1118039',descripcion:'Consigue lo que te propongas. Lleva a cabo tus tareas de la oficina con eficiencia, mantiene tus negocios productivos y tus datos, seguros Diseño más delgado y pequeño con marcos laterales más estrechos, pantalla de 15.6” para que no te pierdas de ningún detalle.'},
    {id:'3',idCategoria:'1',img:'../public/imgProductos/img3.jpg',titulo:'NOTEBOOK CX 30382 I7 1165G7 8GB SSD 240GB 15.6 FREE',precio:'$1399990',descripcion:'Su diseño delgado y ligero hace que sea fácil de transportar y perfecto para llevarlo consigo a cualquier lugar. No importa si necesita utilizarla para trabajar o para entretenimiento, esta notebook es la elección perfecta para satisfacer todas sus necesidades informáticas.'},
    {id:'4',idCategoria:'2',img:'../public/imgProductos/img4.png',titulo:'PLACA DE VIDEO ASUS NVIDIA GEFORCE GTX 1660 SUPER TUF GAMING OC 6GB DUAL',precio:'$543049',descripcion:'-Motor gráfico: NVIDIA® GeForce® GTX 1660 SUPER™\n-Bús: PCI Express 3.0\n-OpenGL: OpenGL®4.6\n-Memoria de video: 6GB GDDR6\n-Reloj del motor:\nModo OC: 1845 MHz (reloj de aumento)\nModo de juego (predeterminado): reloj de aumento de GPU: 1815 MHz, reloj base de GPU: 1530 MHz\n-Núcleo CUDA: 1408\n-Velocidad de memoria: 14002 MHz\n-interfaz de memoria: 192 bits\n-Resolución: Resolución máxima digital 7680 x 4320\n-Interfaz:\nSí x 1 (DVI-D nativo)\nSí x 1 (Nativo HDMI 2.0b)\nSí x 1 (Nativo DisplayPort 1.4)\nCompatibilidad con HDCP Sí (2.2)\n-Soporte máximo de pantalla: 3 \n-Dimensiones: 20.6 x 12.4 x4.6 Centímetro\n-Fuente de alimentación recomendada: 450W\n-Conectores de alimentación: 1x8 pines'},
    {id:'5',idCategoria:'2',img:'../public/imgProductos/img5.png',titulo:'PLACA DE VIDEO PNY NVIDIA GEFORCE RTX 4080 XLR8 GAMING VERTO EPIC X 16GB GDDR6X',precio:'$2683289',descripcion:'-Núcleos CUDA: 9728\n-Velocidad de reloj: 2205 MHz\n-Velocidad de impulso: 2505 MHz\n-Velocidad de memoria (Gbps): 23\n-Tamaño de la memoria: 16GB GDDR6X\n-interfaz de memoria: 256 bits\n-Ancho de banda de memoria (GB/seg): 736\n-Salidas: DisplayPort 1.4a (x3), HDMI 2.1\n-Pantalla multiple: 4\n-Resolución: 7680 x 4320 a 120 Hz (digital)3\n-Entrada de alimentación: 16 pines (Uno de 16 pines a Tres de 8 pines)\n-Tipo de bús: PCI Express 4.0 x16\n-Dimensiones de la tarjeta: 13,06" x 5,39" x 2,8"; ranura 3,5'},
    {id:'6',idCategoria:'3',img:'../public/imgProductos/img6.png',titulo:'MONITOR 27 GIGABYTE G27FC-SA VA FHD 165HZ',precio:'$449990',descripcion:'A menudo se subestima al monitor. La verdad es que los monitores forman un efecto sinérgico y ofrecen el mejor rendimiento de los componentes de la PC. Los monitores para juegos de GIGABYTE ofrecen las mejores especificaciones y calidad, los usuarios realmente pueden disfrutar de un rendimiento de primer nivel sin necesidad de extravagancias.\n\n-Tamaño del panel (diagonal): 27" VA 1500R\n-Área de visualización de pantalla: (HxV) 597,88 x 336,31 (mm)\n-Resolución verdadera: 1920 x 1080 (FHD)\n-Tamaño de píxel: 0 .3114 * 0.3114\n-Ángulo de visión 178 ° (H) / 178 ° (V)\n-Colores de pantalla: 8 bits\n-Tiempo de respuesta: 1 ms (MPRT)\n-Frecuencia de actualización: 165 Hz\n-Entrada de señal: HDMI 1.4 x2, Display Port 1.2 x1\n-Enchufe de audífonos: si\n-Altavoz: 2 W x2\n-Puerto (s) USB: USB 3.0 x2\n-El consumo de energía :55W (máximo)\n-Ángulo de inclinación: -5 ° ~ + 20 °\n-Ajuste de altura (mm): 1 de 30 mm\n-Montaje en pared VESA (mm:) 100 * 100 mm\n-Dimensión con soporte (WxHxD): 610,3 * 531 * 203\n-Dimensión sin soporte (WxHxD): 610,3 * 367,4 * 84,5'}
];

export function DBProductos(){
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(productos)
        }, 200);
    });
};